version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile.develop
    tty: true
    stdin_open: true
    volumes:
      - ./src:/go/merubo/src
    ports:
      - "8080:8080"
    env_file: .env